from googleapiclient.discovery import build
import httplib2
import pandas as pd
from typing import Dict, List, Optional, Tuple
import os
from src.services.anonymization import anonymize_authors_globally
from utils.logger import get_logger

logger = get_logger(__name__)


def _get_http_settings() -> Tuple[int, int]:
    timeout = int(os.getenv("YOUTUBE_HTTP_TIMEOUT_SECONDS", "20"))
    retries = int(os.getenv("YOUTUBE_HTTP_RETRIES", "3"))
    return timeout, retries


def _build_youtube_client(api_key: str) -> Tuple[object, int]:
    timeout, retries = _get_http_settings()
    http = httplib2.Http(timeout=timeout)
    youtube = build(
        "youtube",
        "v3",
        developerKey=api_key,
        cache_discovery=False,
        http=http,
    )
    return youtube, retries


def fetch_youtube_comments(api_key: str, video_id: str) -> List[Dict[str, Optional[str]]]:
    """Fetches all top-level comments for a YouTube video.

    Args:
        api_key: YouTube Data API key with access to ``commentThreads.list``.
        video_id: YouTube video ID to scrape comments from.

    Returns:
        A list of dictionaries containing ``author``, ``text``, ``published_at``,
        and ``like_count``.

    Example usage:
        >>> comments = fetch_youtube_comments(
        ...     api_key="YOUR_API_KEY",
        ...     video_id="dQw4w9WgXcQ",
        ... )
        >>> len(comments) >= 0
        True
    """
    logger.info("Fetching YouTube comments for video_id=%s", video_id)
    youtube, retries = _build_youtube_client(api_key)
    comments = []
    next_page_token = None

    while True:
        response = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=100,
            pageToken=next_page_token,
            textFormat="plainText",
        ).execute(num_retries=retries)

        for item in response.get("items", []):
            snippet = item["snippet"]["topLevelComment"]["snippet"]
            comments.append(
                {
                    "author": snippet.get("authorDisplayName"),
                    "text": snippet.get("textDisplay"),
                    "published_at": snippet.get("publishedAt"),
                    "like_count": snippet.get("likeCount"),
                }
            )

        logger.debug("Fetched page: total_comments=%d", len(comments))
        next_page_token = response.get("nextPageToken")
        if not next_page_token:
            break

    logger.info("Completed fetching comments for video_id=%s total=%d", video_id, len(comments))
    return comments


def fetch_video_metadata(api_key: str, video_id: str) -> Dict[str, Optional[str]]:
    """Fetches video-level metadata (title and description).

    Args:
        api_key: YouTube Data API key with access to ``videos.list``.
        video_id: YouTube video ID.

    Returns:
        Dictionary containing ``video_title`` and ``video_description``.

    Example usage:
        >>> metadata = fetch_video_metadata("YOUR_API_KEY", "dQw4w9WgXcQ")
        >>> "video_title" in metadata
        True
    """
    logger.info("Fetching metadata for video_id=%s", video_id)
    youtube, retries = _build_youtube_client(api_key)
    response = youtube.videos().list(part="snippet", id=video_id, maxResults=1).execute(
        num_retries=retries
    )
    items = response.get("items", [])
    if not items:
        logger.warning("No metadata found for video_id=%s", video_id)
        return {"video_title": None, "video_description": None}

    snippet = items[0].get("snippet", {})
    return {
        "video_title": snippet.get("title"),
        "video_description": snippet.get("description"),
    }


def save_comments_to_csv(comments: List[Dict[str, Optional[str]]], output_path: str) -> None:
    """Persists comments to a CSV file.

    Args:
        comments: Comment payload generated by ``fetch_youtube_comments``.
        output_path: Absolute or relative path to the output CSV file.

    Example usage:
        >>> sample = [{
        ...     "author": "user_a",
        ...     "text": "Great video!",
        ...     "published_at": None,
        ...     "like_count": 3,
        ... }]
        >>> save_comments_to_csv(sample, "scrapper/video_comments.csv")
    """
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    df = pd.DataFrame(comments)
    df.to_csv(output_path, index=False)
    logger.info("Saved %d comments to %s", len(df), output_path)


def fetch_and_save_comments(
    api_key: str,
    video_map: Dict[str, str],
    output_dir: str = "comments",
    anonymize_authors: bool = True,
) -> None:
    """Fetches comments for multiple videos and optionally anonymizes authors.

    Args:
        api_key: YouTube Data API key.
        video_map: Mapping of ``video_id -> output_filename.csv``.
        output_dir: Target directory for generated CSV files.
        anonymize_authors: Applies global author anonymization when ``True``.

    Example usage:
        >>> fetch_and_save_comments(
        ...     api_key="YOUR_API_KEY",
        ...     video_map={"dQw4w9WgXcQ": "video_1.csv"},
        ...     output_dir="comments",
        ...     anonymize_authors=True,
        ... )
    """
    os.makedirs(output_dir, exist_ok=True)
    logger.info("Output directory ready: %s", output_dir)
    file_paths = []

    for video_id, filename in video_map.items():
        logger.info("Processing video_id=%s output=%s", video_id, filename)
        metadata = fetch_video_metadata(api_key, video_id)
        comments = fetch_youtube_comments(api_key, video_id)
        for comment in comments:
            comment["video_id"] = video_id
            comment["video_title"] = metadata.get("video_title")
            comment["video_description"] = metadata.get("video_description")
        output_path = os.path.join(output_dir, filename)
        save_comments_to_csv(comments, output_path)
        file_paths.append(output_path)

    if anonymize_authors:
        logger.info("Applying global author anonymization for %d files", len(file_paths))
        anonymize_authors_globally(file_paths)
        logger.info("Anonymization complete")
    else:
        logger.info("Anonymization skipped (anonymize_authors=False)")
