from __future__ import annotations
import logging
import os
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from dotenv import load_dotenv

# Ensure repo root and src are importable when running via uvicorn.
_ROOT = Path(__file__).resolve().parents[2]
_SRC = _ROOT / "src"
for _path in (str(_ROOT), str(_SRC)):
    if _path not in sys.path:
        sys.path.insert(0, _path)

from pipeline.orchestrator import run_orchestrator
from utils.youtube_url_normalizer import extract_video_id

# Load .env when running the API directly (uvicorn doesn't auto-load it).
load_dotenv()

APP_TITLE = os.getenv("APP_TITLE", "Comment Analytics API")
APP_VERSION = os.getenv("APP_VERSION", "1.0.0")
APP_ENV = os.getenv("APP_ENV", "production")
APP_DEBUG = os.getenv("APP_DEBUG", "false").lower() in {"1", "true", "yes", "on"}
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
OUTPUT_BASE_DIR = os.getenv("OUTPUT_BASE_DIR", str(_ROOT / "outputs"))
MAX_REQUEST_BYTES = int(os.getenv("MAX_REQUEST_BYTES", "2000000"))
ALLOWED_ORIGINS = [o.strip() for o in os.getenv("ALLOWED_ORIGINS", "").split(",") if o.strip()]

logging.basicConfig(level=LOG_LEVEL, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

app = FastAPI(title=APP_TITLE, version=APP_VERSION, debug=APP_DEBUG)
if ALLOWED_ORIGINS:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=ALLOWED_ORIGINS,
        allow_methods=["POST", "GET"],
        allow_headers=["*"],
    )


class OrchestrateRequest(BaseModel):
    """Request payload for running the full comment analytics pipeline."""

    video_input: Optional[str] = Field(None, description="YouTube URL or ID")
    video_inputs: Optional[List[str]] = Field(None, description="List of YouTube URLs/IDs")
    output_dir: str = Field("outputs", description="Output directory")
    output_json_name: Optional[str] = Field(None, description="Optional output JSON file name")
    anonymize_authors: bool = Field(True, description="Mask author names")
    topic_with_llm: bool = Field(True, description="Enable LLM topic labeling")
    save_split_outputs_flag: bool = Field(True, description="Write evidence/insights separately")


class OrchestrateMeta(BaseModel):
    """Metadata for the orchestrator response."""

    request_id: str
    processed_at: str
    duration_ms: int
    items: int


class OrchestrateItem(BaseModel):
    """File references generated by the pipeline."""

    video_id: str
    output_path: str
    evidence_path: Optional[str]
    llm_insights_path: Optional[str]


class OrchestrateResponse(BaseModel):
    """Response payload containing full pipeline outputs."""

    meta: OrchestrateMeta
    results: List[OrchestrateItem]


def _collect_inputs(payload: OrchestrateRequest) -> List[str]:
    """Collects and sanitizes video inputs from request payload.

    Args:
        payload: Incoming request payload.

    Returns:
        List of normalized YouTube URLs/IDs to process.

    Example usage:
        >>> req = OrchestrateRequest(video_input="dQw4w9WgXcQ")
        >>> _collect_inputs(req)
        ['dQw4w9WgXcQ']
    """
    inputs: List[str] = []
    if payload.video_input:
        inputs.append(payload.video_input.strip())
    if payload.video_inputs:
        inputs.extend(item.strip() for item in payload.video_inputs if item and item.strip())
    return [item for item in inputs if item]


def _build_output_name(base_name: Optional[str], idx: int, total: int) -> Optional[str]:
    """Builds a unique output filename for multi-item requests.

    Args:
        base_name: Requested output name, if any.
        idx: Zero-based index of the current item.
        total: Total number of items in the request.

    Returns:
        Output filename with suffix when multiple items are processed.
    """
    if not base_name or total <= 1:
        return base_name
    path = Path(base_name)
    suffix = path.suffix or ".json"
    stem = path.stem
    return f"{stem}_{idx + 1}{suffix}"


def _env_bool(name: str, default: bool) -> bool:
    """Reads a boolean value from environment variables."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: Optional[int]) -> Optional[int]:
    """Reads an integer value from environment variables."""
    value = os.getenv(name)
    if value is None or value == "":
        return default
    try:
        return int(value)
    except ValueError:
        return default


def _resolve_output_dir(output_dir: str) -> str:
    """Resolves output directory within the allowed base directory.

    Args:
        output_dir: Requested relative output directory.

    Returns:
        Absolute, sanitized output directory.
    """
    base = Path(OUTPUT_BASE_DIR).resolve()
    target = (base / output_dir).resolve() if output_dir else base
    if base not in target.parents and target != base:
        raise HTTPException(status_code=400, detail="invalid_output_dir")
    return str(target)


def _sanitize_output_name(name: Optional[str]) -> Optional[str]:
    """Validates output filename to prevent path traversal."""
    if not name:
        return None
    candidate = Path(name)
    if candidate.name != name or ".." in candidate.parts:
        raise HTTPException(status_code=400, detail="invalid_output_json_name")
    return name


def _build_result_paths(
    *,
    output_dir: str,
    output_name: str,
    video_id: str,
    save_split_outputs_flag: bool,
) -> OrchestrateItem:
    """Builds file paths returned to the caller."""
    base = Path(output_dir)
    output_path = str(base / output_name)
    evidence_path = str(base / f"evidence_{video_id}.json") if save_split_outputs_flag else None
    llm_path = (
        str(base / f"llm_insights_{video_id}.json") if save_split_outputs_flag else None
    )
    return OrchestrateItem(
        video_id=video_id,
        output_path=output_path,
        evidence_path=evidence_path,
        llm_insights_path=llm_path,
    )


@app.middleware("http")
async def request_context_middleware(request: Request, call_next):
    """Attaches request id and timing metadata to each response."""
    content_length = request.headers.get("content-length")
    if content_length and int(content_length) > MAX_REQUEST_BYTES:
        raise HTTPException(status_code=413, detail="request_too_large")
    request_id = request.headers.get("X-Request-ID") or str(uuid.uuid4())
    request.state.request_id = request_id
    start_time = time.perf_counter()
    response = await call_next(request)
    duration_ms = int((time.perf_counter() - start_time) * 1000)
    response.headers["X-Request-ID"] = request_id
    response.headers["X-Process-Time-MS"] = str(duration_ms)
    return response


@app.get("/health")
def health() -> Dict[str, str]:
    """Health check endpoint for service monitoring."""
    return {
        "status": "ok",
        "version": APP_VERSION,
        "environment": APP_ENV,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


@app.get("/")
def root() -> Dict[str, str]:
    """Root endpoint with quick navigation hints."""
    return {
        "message": "Comment Analytics API is running.",
        "health": "/health",
        "analyze": "/analyze",
        "docs": "/docs",
        "results": "/results/{filename}",
    }


@app.get("/results/{filename}")
def get_result_file(filename: str) -> FileResponse:
    """Downloads a generated JSON result file by filename."""
    if not filename or "/" in filename or "\\" in filename:
        raise HTTPException(status_code=400, detail="invalid_filename")
    base = Path(OUTPUT_BASE_DIR).resolve()
    target = (base / filename).resolve()
    if base not in target.parents:
        raise HTTPException(status_code=400, detail="invalid_filename")
    if not target.exists():
        raise HTTPException(status_code=404, detail="file_not_found")
    return FileResponse(str(target), media_type="application/json")


@app.post("/analyze", response_model=OrchestrateResponse)
def orchestrate(payload: OrchestrateRequest, request: Request) -> OrchestrateResponse:
    """Runs the full pipeline for one or more YouTube inputs.

    Args:
        payload: Request body containing inputs and options.
        request: FastAPI request context.

    Returns:
        OrchestrateResponse with metadata and full results.
    """
    inputs = _collect_inputs(payload)
    if not inputs:
        raise HTTPException(status_code=400, detail="video_input or video_inputs is required")

    start_time = time.perf_counter()
    results: List[OrchestrateItem] = []
    total = len(inputs)

    safe_output_dir = _resolve_output_dir(payload.output_dir)
    logger.info("Orchestrate started: items=%s request_id=%s", total, request.state.request_id)
    for idx, video_input in enumerate(inputs):
        base_name = _sanitize_output_name(payload.output_json_name)
        output_name = _build_output_name(base_name, idx, total)
        video_id = extract_video_id(video_input)
        try:
            run_orchestrator(
                video_input=video_input,
                api_key=None,
                output_dir=safe_output_dir,
                output_json_name=output_name,
                anonymize_authors=payload.anonymize_authors,
                topic_with_llm=payload.topic_with_llm,
                llm_model=os.getenv("OLLAMA_MODEL"),
                llm_base_url=os.getenv("OLLAMA_BASE_URL"),
                llm_enabled=_env_bool("LLM_ENABLED", True),
                llm_batch_size=_env_int("LLM_BATCH_SIZE", None),
                llm_comment_limit=_env_int("LLM_COMMENT_LIMIT", None),
                llm_include_history=(
                    None
                    if os.getenv("LLM_INCLUDE_HISTORY") is None
                    else _env_bool("LLM_INCLUDE_HISTORY", True)
                ),
                llm_timeout_seconds=_env_int("OLLAMA_TIMEOUT", None),
                llm_provider=os.getenv("LLM_PROVIDER"),
                llm_api_key=os.getenv("LLM_API_KEY"),
                llm_api_base_url=os.getenv("LLM_API_BASE_URL"),
                llm_simple_mode=(
                    None
                    if os.getenv("LLM_SIMPLE_MODE") is None
                    else _env_bool("LLM_SIMPLE_MODE", False)
                ),
                save_split_outputs_flag=payload.save_split_outputs_flag,
            )
        except ValueError as exc:
            logger.warning("Bad request: %s", exc)
            raise HTTPException(status_code=400, detail=str(exc)) from exc
        except Exception as exc:  # pragma: no cover - defensive guard
            logger.exception("Orchestrator failed")
            raise HTTPException(status_code=500, detail="internal_server_error") from exc

        results.append(
            _build_result_paths(
                output_dir=safe_output_dir,
                output_name=output_name or f"orchestrator_{video_id}.json",
                video_id=video_id,
                save_split_outputs_flag=payload.save_split_outputs_flag,
            )
        )

    duration_ms = int((time.perf_counter() - start_time) * 1000)
    meta = OrchestrateMeta(
        request_id=request.state.request_id,
        processed_at=datetime.now(timezone.utc).isoformat(),
        duration_ms=duration_ms,
        items=len(results),
    )
    return OrchestrateResponse(meta=meta, results=results)
